[build]
  command = "yarn build"
  publish = "public/"
  functions = "functions/"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[context.production]
  environment = { FAUNADB_ADMIN_SECRET = "fnAD4xSLvbACCS_OF0hsKwxFkYAFIagSxJzkrG1l"}